//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libvirt.Model {
    
    
    [System.Xml.Serialization.XmlTypeAttribute("clusterSize", Namespace="")]
    public partial class StorageClusterSize {
        
        private string value;
        
        private string unit;
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.value;
            }
            set {
                this.value = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("unit")]
        public string Unit {
            get {
                return this.unit;
            }
            set {
                this.unit = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("encryption", Namespace="")]
    public partial class StorageEncryption {
        
        private StorageEncryptionFormat format;
        
        private StorageEncryptionEngine engine;
        
        private bool engineSpecified;
        
        private StorageSecret secret;
        
        private StorageEncryptionCipher cipher;
        
        private StorageEncryptionIvgen ivgen;
        
        [System.Xml.Serialization.XmlAttributeAttribute("format")]
        public StorageEncryptionFormat Format {
            get {
                return this.format;
            }
            set {
                this.format = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("engine")]
        public StorageEncryptionEngine Engine {
            get {
                return this.engine;
            }
            set {
                this.engine = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EngineSpecified {
            get {
                return this.engineSpecified;
            }
            set {
                this.engineSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("secret", Namespace="")]
        public StorageSecret Secret {
            get {
                return this.secret;
            }
            set {
                this.secret = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("cipher", Namespace="")]
        public StorageEncryptionCipher Cipher {
            get {
                return this.cipher;
            }
            set {
                this.cipher = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ivgen", Namespace="")]
        public StorageEncryptionIvgen Ivgen {
            get {
                return this.ivgen;
            }
            set {
                this.ivgen = value;
            }
        }
    }
    
    public partial class StorageEncryptionCipher {
        
        private string name;
        
        private uint size;
        
        private string mode;
        
        private string hash;
        
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name {
            get {
                return this.name;
            }
            set {
                this.name = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("size")]
        public uint Size {
            get {
                return this.size;
            }
            set {
                this.size = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("mode")]
        public string Mode {
            get {
                return this.mode;
            }
            set {
                this.mode = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("hash")]
        public string Hash {
            get {
                return this.hash;
            }
            set {
                this.hash = value;
            }
        }
    }
    
    public enum StorageEncryptionEngine {
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="qemu")]
        Qemu,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="librbd")]
        Librbd,
    }
    
    public enum StorageEncryptionFormat {
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="default")]
        Default,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="qcow")]
        Qcow,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="luks")]
        Luks,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="luks2")]
        Luks2,
    }
    
    public partial class StorageEncryptionIvgen {
        
        private string name;
        
        private string hash;
        
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name {
            get {
                return this.name;
            }
            set {
                this.name = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("hash")]
        public string Hash {
            get {
                return this.hash;
            }
            set {
                this.hash = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("features", Namespace="")]
    public partial class StorageFileFormatFeatures {
        
        private StorageFileFormatFeaturesLazyRefcounts lazyRefcounts;
        
        private StorageFileFormatFeaturesExtendedL2 extendedL2;
        
        [System.Xml.Serialization.XmlElementAttribute("lazy_refcounts", Namespace="")]
        public StorageFileFormatFeaturesLazyRefcounts LazyRefcounts {
            get {
                return this.lazyRefcounts;
            }
            set {
                this.lazyRefcounts = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("extended_l2", Namespace="")]
        public StorageFileFormatFeaturesExtendedL2 ExtendedL2 {
            get {
                return this.extendedL2;
            }
            set {
                this.extendedL2 = value;
            }
        }
    }
    
    public partial class StorageFileFormatFeaturesExtendedL2 {
    }
    
    public partial class StorageFileFormatFeaturesLazyRefcounts {
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("permissions", Namespace="")]
    public partial class StoragePermissions {
        
        private uint mode;
        
        private bool modeSpecified;
        
        private long owner;
        
        private bool ownerSpecified;
        
        private long group;
        
        private bool groupSpecified;
        
        private string label;
        
        [System.Xml.Serialization.XmlElementAttribute("mode", Namespace="")]
        public uint Mode {
            get {
                return this.mode;
            }
            set {
                this.mode = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModeSpecified {
            get {
                return this.modeSpecified;
            }
            set {
                this.modeSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("owner", Namespace="")]
        public long Owner {
            get {
                return this.owner;
            }
            set {
                this.owner = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OwnerSpecified {
            get {
                return this.ownerSpecified;
            }
            set {
                this.ownerSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("group", Namespace="")]
        public long Group {
            get {
                return this.group;
            }
            set {
                this.group = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupSpecified {
            get {
                return this.groupSpecified;
            }
            set {
                this.groupSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("label", Namespace="")]
        public string Label {
            get {
                return this.label;
            }
            set {
                this.label = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("secret", Namespace="")]
    public partial class StorageSecret {
        
        private string type;
        
        private string uuid;
        
        private string usage;
        
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type {
            get {
                return this.type;
            }
            set {
                this.type = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("uuid")]
        public string Uuid {
            get {
                return this.uuid;
            }
            set {
                this.uuid = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("usage")]
        public string Usage {
            get {
                return this.usage;
            }
            set {
                this.usage = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("volume", Namespace="")]
    public partial class Vol {
        
        private VolType type;
        
        private bool typeSpecified;
        
        private string name;
        
        private string key;
        
        private VolSource source;
        
        private VolSizingCapacity capacity;
        
        private VolSizingAllocation allocation;
        
        private VolSizingPhysical physical;
        
        private VolTarget target;
        
        private VolBackingStore backingStore;
        
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public VolType Type {
            get {
                return this.type;
            }
            set {
                this.type = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeSpecified;
            }
            set {
                this.typeSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("name", Namespace="")]
        public string Name {
            get {
                return this.name;
            }
            set {
                this.name = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("key", Namespace="")]
        public string Key {
            get {
                return this.key;
            }
            set {
                this.key = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("source", Namespace="")]
        public VolSource Source {
            get {
                return this.source;
            }
            set {
                this.source = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("capacity", Namespace="")]
        public VolSizingCapacity Capacity {
            get {
                return this.capacity;
            }
            set {
                this.capacity = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("allocation", Namespace="")]
        public VolSizingAllocation Allocation {
            get {
                return this.allocation;
            }
            set {
                this.allocation = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("physical", Namespace="")]
        public VolSizingPhysical Physical {
            get {
                return this.physical;
            }
            set {
                this.physical = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("target", Namespace="")]
        public VolTarget Target {
            get {
                return this.target;
            }
            set {
                this.target = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("backingStore", Namespace="")]
        public VolBackingStore BackingStore {
            get {
                return this.backingStore;
            }
            set {
                this.backingStore = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("backingStore", Namespace="")]
    public partial class VolBackingStore {
        
        private string path;
        
        private VolFormat format;
        
        private StoragePermissions permissions;
        
        private VolTimestamps timestamps;
        
        [System.Xml.Serialization.XmlElementAttribute("path", Namespace="")]
        public string Path {
            get {
                return this.path;
            }
            set {
                this.path = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("format", Namespace="")]
        public VolFormat Format {
            get {
                return this.format;
            }
            set {
                this.format = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("permissions", Namespace="")]
        public StoragePermissions Permissions {
            get {
                return this.permissions;
            }
            set {
                this.permissions = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("timestamps", Namespace="")]
        public VolTimestamps Timestamps {
            get {
                return this.timestamps;
            }
            set {
                this.timestamps = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("extent", Namespace="")]
    public partial class VolDevextents {
        
        private ulong start;
        
        private ulong end;
        
        [System.Xml.Serialization.XmlAttributeAttribute("start")]
        public ulong Start {
            get {
                return this.start;
            }
            set {
                this.start = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("end")]
        public ulong End {
            get {
                return this.end;
            }
            set {
                this.end = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("format", Namespace="")]
    public partial class VolFormat {
        
        private VolFormatType type;
        
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public VolFormatType Type {
            get {
                return this.type;
            }
            set {
                this.type = value;
            }
        }
    }
    
    public enum VolFormatType {
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="unknown")]
        Unknown,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="raw")]
        Raw,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="dir")]
        Dir,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="bochs")]
        Bochs,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="cloop")]
        Cloop,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="dmg")]
        Dmg,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="iso")]
        Iso,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="vpc")]
        Vpc,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="vdi")]
        Vdi,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="fat")]
        Fat,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="vhd")]
        Vhd,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="ploop")]
        Ploop,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="luks")]
        Luks,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="cow")]
        Cow,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="qcow")]
        Qcow,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="qcow2")]
        Qcow2,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="qed")]
        Qed,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="vmdk")]
        Vmdk,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="none")]
        None,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="auto")]
        Auto,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="ext2")]
        Ext2,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="ext3")]
        Ext3,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="ext4")]
        Ext4,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="ufs")]
        Ufs,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="iso9660")]
        Iso9660,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="udf")]
        Udf,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="gfs")]
        Gfs,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="gfs2")]
        Gfs2,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="vfat")]
        Vfat,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="hfs+")]
        HfsPlus,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="xfs")]
        Xfs,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="ocfs2")]
        Ocfs2,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="vmfs")]
        Vmfs,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="linux")]
        Linux,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="fat16")]
        Fat16,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="fat32")]
        Fat32,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="linux-swap")]
        LinuxSwap,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="linux-lvm")]
        LinuxLvm,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="linux-raid")]
        LinuxRaid,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="extended")]
        Extended,
    }
    
    public partial class VolSizingAllocation {
        
        private string value;
        
        private string unit;
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.value;
            }
            set {
                this.value = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("unit")]
        public string Unit {
            get {
                return this.unit;
            }
            set {
                this.unit = value;
            }
        }
    }
    
    public partial class VolSizingCapacity {
        
        private string value;
        
        private string unit;
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.value;
            }
            set {
                this.value = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("unit")]
        public string Unit {
            get {
                return this.unit;
            }
            set {
                this.unit = value;
            }
        }
    }
    
    public partial class VolSizingPhysical {
        
        private string value;
        
        private string unit;
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.value;
            }
            set {
                this.value = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("unit")]
        public string Unit {
            get {
                return this.unit;
            }
            set {
                this.unit = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("source", Namespace="")]
    public partial class VolSource {
        
        private VolSourcedev[] device;
        
        [System.Xml.Serialization.XmlElementAttribute("device", Namespace="")]
        public VolSourcedev[] Device {
            get {
                return this.device;
            }
            set {
                this.device = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("device", Namespace="")]
    public partial class VolSourcedev {
        
        private string path;
        
        private VolDevextents[] extent;
        
        [System.Xml.Serialization.XmlAttributeAttribute("path")]
        public string Path {
            get {
                return this.path;
            }
            set {
                this.path = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("extent", Namespace="")]
        public VolDevextents[] Extent {
            get {
                return this.extent;
            }
            set {
                this.extent = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("target", Namespace="")]
    public partial class VolTarget {
        
        private string path;
        
        private VolFormat format;
        
        private StoragePermissions permissions;
        
        private VolTimestamps timestamps;
        
        private StorageEncryption encryption;
        
        private string compat;
        
        private VolTargetNocow nocow;
        
        private StorageClusterSize clusterSize;
        
        private StorageFileFormatFeatures features;
        
        [System.Xml.Serialization.XmlElementAttribute("path", Namespace="")]
        public string Path {
            get {
                return this.path;
            }
            set {
                this.path = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("format", Namespace="")]
        public VolFormat Format {
            get {
                return this.format;
            }
            set {
                this.format = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("permissions", Namespace="")]
        public StoragePermissions Permissions {
            get {
                return this.permissions;
            }
            set {
                this.permissions = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("timestamps", Namespace="")]
        public VolTimestamps Timestamps {
            get {
                return this.timestamps;
            }
            set {
                this.timestamps = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("encryption", Namespace="")]
        public StorageEncryption Encryption {
            get {
                return this.encryption;
            }
            set {
                this.encryption = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("compat", Namespace="")]
        public string Compat {
            get {
                return this.compat;
            }
            set {
                this.compat = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("nocow", Namespace="")]
        public VolTargetNocow Nocow {
            get {
                return this.nocow;
            }
            set {
                this.nocow = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("clusterSize", Namespace="")]
        public StorageClusterSize ClusterSize {
            get {
                return this.clusterSize;
            }
            set {
                this.clusterSize = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("features", Namespace="")]
        public StorageFileFormatFeatures Features {
            get {
                return this.features;
            }
            set {
                this.features = value;
            }
        }
    }
    
    public partial class VolTargetNocow {
    }
    
    [System.Xml.Serialization.XmlTypeAttribute("timestamps", Namespace="")]
    public partial class VolTimestamps {
        
        private string atime;
        
        private string btime;
        
        private string ctime;
        
        private string mtime;
        
        [System.Xml.Serialization.XmlElementAttribute("atime", Namespace="")]
        public string Atime {
            get {
                return this.atime;
            }
            set {
                this.atime = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("btime", Namespace="")]
        public string Btime {
            get {
                return this.btime;
            }
            set {
                this.btime = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ctime", Namespace="")]
        public string Ctime {
            get {
                return this.ctime;
            }
            set {
                this.ctime = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("mtime", Namespace="")]
        public string Mtime {
            get {
                return this.mtime;
            }
            set {
                this.mtime = value;
            }
        }
    }
    
    public enum VolType {
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="file")]
        File,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="block")]
        Block,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="dir")]
        Dir,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="network")]
        Network,
        
        [System.Xml.Serialization.XmlEnumAttribute(Name="netdir")]
        Netdir,
    }
}
